#!/bin/bash
echo -e "\033[1;32mQual dominio vc deseja adicionar ?\033[0m"
read -p ": " domi
echo "$domi" >> /etc/payload
squid3 -k reconfigure 2> /dev/null
squid -k reconfigure 2> /dev/null
echo -e "\033[1;31m$domi Foi adicionado\033[0m"
