#!/bin/bash
clear
echo -e "\033[1;33mUserback options:\033[1;30m
1) Deletar usuario
2) Deletar e desconectar todos do usuario
3) Desconectar todos do usuario\033[0m"
read -p ": " option
 if [ $option -eq 1 ]; then
 read -p "Qual o nome do usuario: " name
 if [ $(cat /etc/passwd |grep "^$name:" |wc -l) -eq 0 ]; then
 echo "Usuario não existe"
 exit
 fi
 userdel --force $name > /dev/null 2>/dev/null
 echo "Usuario $name foi deletado"
 exit
 fi

 if [ $option -eq 2 ]; then
 read -p "Qual o nome do usuario: " name
 if [ $(cat /etc/passwd |grep "^$name:" |wc -l) -eq 0 ]; then
 echo "Usuario não existe"
 exit
 fi
 pids=$(ps -u $name |awk {'print $1'})
 kill "$pids" >/dev/null 2>/dev/null
 userdel $name 1>/dev/null 2>/dev/null
 echo "Usuario $name foi parado e deletado"
 exit
 fi

 if [ $option -eq 3 ]; then
 read -p "Qual o nome do usuario: " name
 if [ $(cat /etc/passwd |grep "^$name:" |wc -l) -eq 0 ]; then
 echo "Usuario não existe"
 exit
 fi
 pids=$(ps -u $name |awk {'print $1'})
 kill "$pids" >/dev/null 2>/dev/null
 echo "Usuario $name foi parado"
 exit
 fi
