#!/bin/bash

while true; do

echo -e "\033[1;30m  - - - - - - - - - - - - - - - - - - - - - - -\033[0m"
echo -e "\033[1;32m       Usuario : Conexoes S \033[0m"
echo -e "\033[1;30m  - - - - - - - - - - - - - - - - - - - - - - -\033[0m"
        for usur in `awk -F : '$3 >= 700 { print $1 }' /etc/passwd |grep -v "nobody"`; do
	usurnum=$(ps aux |grep -vi '[a-z]$usur' |grep -vi '$usur[a-z]' |grep -v '[1-9]$usur' |grep -v '$usur[1-9]' |grep $usur |grep $usur |grep 'sshd' |cut -d' ' -f1 |grep $usur |wc -l)
        pidrnf=$(ps aux |grep -vi '[a-z]$usur' |grep -vi '$usur[a-z]' |grep -v '[1-9]$usur' |grep -v '$usur[1-9]' |grep $usur |grep $usur |grep 'sshd' |cut -d' ' -f1,5,6,7,8 |awk {'print $2'})
        echo -e "\033[1;34m       $usur : $usurnum \033[0m"
        echo -e "\033[1;30m  - - - - - - - - - - - - - - - - - - - - - - -\033[0m"
        done
sleep 6s
clear
done
