#!/bin/bash

read -p "Qual o nome do usuario a redefinir: " namer
 if cat /etc/passwd |grep $namer |grep -vi "[a-z]$namer" |grep -vi "$namer[a-z]" |grep -v "[0-9]$namer" |grep -v "$namer[0-9]" |grep $namer > /dev/null
 then
 echo " "
 else
 clear
 echo "Usuario $namer não existe"
 exit
 fi
clear
echo -e "\033[1;26mO que vc deseja redefinir ?
1) Numero de logins
2) Data de expiraçao"
read -p "opção: " option
if [ $option -eq 1 ]; then
read -p "Qual o novo limite de logins: " liml
rm /etc/usuarios/$namer.sh
rm /etc/tempo/$namer.sh
limit $namer $liml
exit 0
fi

if [ $option -eq 2 ]; then
read -p "Qual a atual senha do usuario $namer? : " pass
echo "Qual a nova data : formato DD/MM/AAAA"
read -p ": " date
userdel --force $namer 2> /dev/null
useradd -e $date -M -s /bin/false $namer
(echo $pass ; echo $pass) | passwd $namer > /dev/null 2> /dev/null
echo -e "\033[1;31mUsuario $namer Date: $date\033[0m"
exit
fi
echo -e "essa opçao não existe\033[0m"
