#!/bin/bash

if [ $(id -u) -eq 0 ]
then
	clear
else
	if echo $(id) |grep sudo > /dev/null
	then
	clear
	echo "Voce não é root"
	echo "Seu usuario esta no grupo sudo"
	echo -e "Para virar root execute \033[1;31msudo su\033[0m"
	exit
	else
	clear
	echo -e "Vc nao esta como usuario root, nem com seus direitos (sudo)\nPara virar root execute \033[1;31msu\033[0m e digite sua senha root"
	exit
	fi
fi

echo -e "     \033[40;1;37m  VpsPacket  By Luiz Henrique \033[0m"
echo -e "\033[1;37mEscolha uma das opçoẽs:    \033[1;37mPara Sair Ctrl + C\033[1;33m
[1] Limit \033[1;30m(limite de conexoes simultaneas)\033[1;33m
[2] UserCreate \033[1;30m(Criar usuarios)\033[1;33m
[3] UserRedefine \033[1;30m(Opções para mudanças no usuario)\033[1;33m
[4] UserBack \033[1;30m(Deletar, Desconectar, Opções)\033[1;33m
[5] Firewall-block \033[1;30m(Regras iptables block torrent, icmp [RISCOS])\033[1;33m
[6] ResetFirewall \033[1;30m(Retira todas as regras iptables [RISCOS])\033[1;33m
[7] Istall-addhosts \033[1;30m(Faz a preparaçao para add-host)\033[1;33m
[8] Add-host \033[1;30m(Adicionar hosts aceitos pelo squid )\033[1;33m
[9] Monitoring \033[1;30m(IMPORTANTE monitorar conexões por usuarios)\033[0m\033[1;33m
[10] Detalhes \033[1;30m(Detalhes sobre o VpsPack)\033[1;33m
[11] Desinstalar \033[1;30m(Remover o VpsPack)\033[0m"
read -p ": " opcao

case $opcao in
 1)
  read -p "Usuario: " user
  read -p "Limite de Conexoes: " limit
  limit $user $limit;;
 2)
  Usercreate;;
 3)
  UserRedefine;;
 4)
  UserBack;;
 5)
  firewall-block;;
 6)
  ResetFirewall;;
 7)
  install-addhost;;
 8)
  add-host;;
 9)
  Monitoring;;
 10)
  Detalhes;; 
 11)
  Desinstalar;;
 *)
  id > /dev/null 2> /dev/null
esac
